export const initialState = { 
    titleValue: "",
    listingTypeValue: "",
    descriptionValue: "",
    areaValue: "",
    boroughValue: "",
    latitudeValue: "",
    longitudeValue: "",
    propertyStatusValue: "",
    priceValue: "",
    rentalFrequencyValue: "",
    roomsValue: "",
    furnishedValue: false,
    poolValue: false,
    elevatorValue: false,
    cctvValue: false,
    parkingValue: false,
    pictureValue: "",
    mapInstance:null,
    markerPosition:{lat: '51.51', lng: '-0.0782'}, 
    uploadedImages:[],
    sendRequest: 0,
    userProfile: {
        agencyName: '', 
        phone: '',
        agencyPicture:'',
        bio: '',
        sellerId:'',
        sellerListings:''
    },
    dataIsLoading: true,
	listingInfo: "",
	sellerProfileInfo: "",
	openSnack: false,
	disabledBtn: false,
    agencyNameValue: '', 
    phoneValue:'', 
    bioValue:'', 
    uploadedPictureProfileValue: [],
    profilePicture:'',
    token:'',
    
}