# Generated by Django 4.0.6 on 2022-07-13 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Envelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envelope_name', models.CharField(max_length=50)),
                ('income_or_expense', models.CharField(choices=[('+', 'income'), ('-', 'expense')], max_length=1)),
                ('limit', models.IntegerField()),
                ('common', models.CharField(choices=[('y', 'yes'), ('n', 'no')], default='n', max_length=1)),
                ('savings', models.CharField(choices=[('y', 'yes'), ('n', 'no')], default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=50)),
                ('my_place', models.CharField(choices=[('y', 'yes'), ('n', 'no')], default='y', max_length=1)),
                ('savings', models.CharField(choices=[('y', 'yes'), ('n', 'no')], default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='envelope_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Spending_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('priority', models.IntegerField()),
                ('comment', models.CharField(max_length=140)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='envelope_app.currency')),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='envelope_app.envelope')),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exchange_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_or_expense', models.CharField(choices=[('+', 'income'), ('-', 'expense')], max_length=1)),
                ('comment', models.CharField(max_length=140)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='envelope_app.currency')),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='envelope_app.envelope')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='envelope_app.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='envelope_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Income_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('comment', models.CharField(max_length=140)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='envelope_app.currency')),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='envelope_app.envelope')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='envelope_app.place')),
            ],
        ),
    ]
