# Generated by Django 4.0.6 on 2022-07-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelope_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='comment',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
