# Generated by Django 4.0.2 on 2022-07-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysiteapp', '0002_alter_post_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email_adress',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
